const {chromium}=require('C:/Users/Arline/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict');
const base=process.env.GAME_URL||'http://127.0.0.1:8771/Solitaire-And-Friends/';
async function targets(p){const bad=await p.locator('button:visible,select:visible,input[type=range]:visible,input[type=checkbox]:visible').evaluateAll(es=>es.filter(e=>{const r=(e.type==='checkbox'?e.closest('label'):e).getBoundingClientRect();return r.width<47.5||r.height<47.5;}).map(e=>e.outerHTML));assert.deepEqual(bad,[],'48px interactive hit areas');}
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{
 const c=await b.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.addInitScript(()=>{window.paintCount=0;const original=CanvasRenderingContext2D.prototype.drawImage;CanvasRenderingContext2D.prototype.drawImage=function(...a){paintCount++;return original.apply(this,a);};});
 await p.goto(base);await p.waitForSelector('.scene-particles[data-active=true]');assert.equal(await p.locator('.scene-particles').getAttribute('data-cards'),'16');assert.equal(await p.getByRole('button',{name:'More games',exact:true}).count(),0);await targets(p);
 await p.waitForSelector('.scene-particles[data-active=false]');const painted=await p.evaluate(()=>paintCount);assert.ok(painted>0,'Opening draws real cards');await p.waitForTimeout(250);assert.equal(await p.evaluate(()=>paintCount),painted,'Opening stops rendering');
 await p.locator('#startGame').click();await p.waitForFunction(()=>window.__sol?.ready);await p.waitForSelector('.board:not(.dealing)');
 assert.equal(await p.locator('.card img.cf').count(),52);assert.equal(await p.locator('.card[data-image-state=ready]').count(),52);
 assert.equal(await p.locator('.card').evaluateAll(es=>es.filter(e=>getComputedStyle(e).willChange.includes('transform')).length),0);
 await p.evaluate(()=>{window.originalFaces=new Map([...document.querySelectorAll('.card')].map(e=>[e.dataset.id,e.querySelector('img')]));for(let i=0;i<60;i++)document.querySelector('.slot.stock').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter'}));});
 assert.ok(await p.evaluate(()=>[...document.querySelectorAll('.card')].every(e=>e.querySelector('img')===originalFaces.get(e.dataset.id))),'Face nodes survive repeated draw/recycle/down/up');
 const saved=await p.evaluate(()=>window.__sol.state);await p.getByRole('button',{name:'Home',exact:true}).click();assert.equal(await p.locator('.scene-particles').getAttribute('data-active'),'false','Home does not replay boot');
 await p.reload();await p.waitForSelector('.scene-particles[data-active=true]');await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});const hiddenPaint=await p.evaluate(()=>paintCount);await p.waitForTimeout(200);assert.equal(await p.evaluate(()=>paintCount),hiddenPaint,'Hidden page stops rendering');await p.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});assert.deepEqual(await p.evaluate(()=>JSON.parse(localStorage.getItem('solitaire-friends-game-v1')).state),saved,'Cold saved-game opening cannot mutate cards');
 await p.getByRole('button',{name:'Settings',exact:true}).click();await p.getByRole('dialog').waitFor();await p.waitForTimeout(260);await targets(p);
 const sheet=await p.getByRole('dialog').boundingBox();assert.ok(Math.abs(sheet.y+sheet.height-844)<2,'Phone sheet anchors to bottom');
 await p.goBack();await p.getByRole('dialog').waitFor({state:'hidden'});assert.equal(await p.evaluate(()=>document.activeElement?.getAttribute('aria-label')),'Settings','Back restores focus');
 await p.locator('#startGame').click();await p.waitForFunction(()=>window.__sol?.ready);await p.locator('#hintBtn').click();await targets(p);
 await p.setViewportSize({width:844,height:390});await p.waitForTimeout(300);await targets(p);await p.getByRole('button',{name:'Settings',exact:true}).click();await p.waitForTimeout(260);await targets(p);
 const fit=await p.getByRole('dialog').evaluate(e=>({r:e.getBoundingClientRect().toJSON(),overflow:e.scrollHeight>e.clientHeight}));assert.ok(fit.r.y>=0&&fit.r.bottom<=390&&!fit.overflow,'Landscape sheet fits');await p.screenshot({path:'tools/polish-settings-landscape.png'});
 await p.getByRole('button',{name:'Close',exact:true}).click();await p.getByRole('dialog').waitFor({state:'hidden'});await p.screenshot({path:'tools/polish-game-landscape.png'});assert.deepEqual(errors,[]);await c.close();
 // Slow images keep the playable board hidden until decode completes.
 const slow=await b.newContext({serviceWorkers:'block'}),sp=await slow.newPage();await sp.route('**/assets/cards/royal/*.png',async r=>{await new Promise(x=>setTimeout(x,800));await r.continue();});await sp.goto(base+'games/solitaire/');await sp.waitForFunction(()=>window.__sol);assert.equal(await sp.evaluate(()=>window.__sol.ready),false);assert.equal(await sp.locator('#board').isVisible(),false);await sp.waitForFunction(()=>window.__sol.ready);assert.equal(await sp.locator('#board').isVisible(),true);await slow.close();
 // Network and decode failures produce readable fallback, even after flips.
 for(const failure of ['network','decode']){const fc=await b.newContext({serviceWorkers:'block'}),fp=await fc.newPage();if(failure==='network')await fp.route('**/heart_1.png',r=>r.abort());else await fp.addInitScript(()=>{const original=HTMLImageElement.prototype.decode;HTMLImageElement.prototype.decode=function(){return this.src.endsWith('heart_1.png')?Promise.reject(Error('Decode failure test')):original.call(this);};});
 await fp.goto(base+'games/solitaire/');await fp.waitForFunction(()=>window.__sol?.ready);const card=fp.locator('.card[data-id="13"]');assert.equal(await card.getAttribute('data-image-state'),'fallback');await fp.evaluate(()=>{for(let i=0;i<52;i++){if(document.querySelector('.card[data-id="13"]').classList.contains('up'))break;document.querySelector('.slot.stock').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter'}));}});
 // If ace is buried in a tableau, inspect its visual without altering the engine.
 await card.evaluate(e=>{e.classList.remove('down');e.classList.add('up','red');});assert.ok(await card.locator('.face-fallback').isVisible());assert.match(await card.locator('.face-fallback').innerText(),/A ♥/);assert.equal(await fp.locator('.card img.cf').count(),52);await fc.close();}
 for(const appPreference of [false,true]){const rc=await b.newContext({serviceWorkers:'block',reducedMotion:appPreference?'no-preference':'reduce'});if(appPreference)await rc.addInitScript(()=>localStorage.setItem('solitaire-friends-settings-v1',JSON.stringify({reducedMotion:true})));const rp=await rc.newPage();await rp.goto(base);await rp.waitForSelector('#startGame:enabled');assert.equal(await rp.locator('.scene-particles').getAttribute('data-active'),'false');await rc.close();}
 console.log('PASS stable 52 decoded faces, missing/decode fallback, load gate, transient layers, bounded saved-safe intro, reduced motion, 48px targets, bottom sheet/Back/focus and landscape fit');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
