import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './scene.css';

const base=new URL(import.meta.env.BASE_URL,location.origin);
const asset=path=>new URL(path,base).href;
const load=path=>import(/* @vite-ignore */ asset(path));
const audioPromise=Promise.all([load('assets/js/sfx.js'),load('assets/js/music.js'),load('assets/js/preferences.js')]).then(([s,m,p])=>({sfx:s.default,music:m.default,...p}));
const time=n=>Math.floor((n||0)/60)+':'+String((n||0)%60).padStart(2,'0');
function Icon({name}){
 const paths={settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1Z',sound:'M4 9h4l5-5v16l-5-5H4Z M16 8q6 4 0 8 M19 4q9 8 0 16',mute:'M4 9h4l5-5v16l-5-5H4Z M17 9l5 6 M22 9l-5 6',shuffle:'M3 6h4c5 0 5 12 10 12h4 M18 15l3 3-3 3 M3 18h4c5 0 5-12 10-12h4 M18 3l3 3-3 3',undo:'M8 5L3 10l5 5 M3 10h10a7 7 0 0 1 0 14',reverse:'M11 5L3 12l8 7Z M21 5l-8 7 8 7Z',hint:'M12 2l2.5 7.5L22 12l-7.5 2.5L12 22l-2.5-7.5L2 12l7.5-2.5Z',gift:'M3 10h18v4H3Z M5 14v8h14v-8 M12 10v12 M12 10C2 10 5 1 10 5l2 5c10 0 7-9 2-5Z',back:'M15 4l-8 8 8 8',play:'M7 3l15 9-15 9Z',close:'M5 5l14 14 M19 5L5 19',trophy:'M7 3h10v8a5 5 0 0 1-10 0Z M7 5H3v4a5 5 0 0 0 5 5 M17 5h4v4a5 5 0 0 1-5 5 M12 16v5 M8 22h8',cards:'M6 3h12v18H6Z M3 6v15 M21 6v15',spade:'M12 3C8 8 3 10 3 14c0 5 5 6 9 2 4 4 9 3 9-2 0-4-5-6-9-11Z M12 16l-3 6h6Z',heart:'M12 21C-6 8 6-3 12 7c6-10 18 1 0 14Z',diamond:'M12 2l9 10-9 10-9-10Z',dice:'M4 3h16v18H4Z M8 7h.1 M16 7h.1 M12 12h.1 M8 17h.1 M16 17h.1',star:'M12 2l3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1Z',ball:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20 M2 12h20 M12 2q-8 10 0 20 M12 2q8 10 0 20',share:'M8 12l10-7 M8 12l10 7 M5 9a3 3 0 1 0 0 6 3 3 0 0 0 0-6 M20 2a3 3 0 1 0 0 6 3 3 0 0 0 0-6 M20 16a3 3 0 1 0 0 6 3 3 0 0 0 0-6'};
 return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={paths[name]||paths.star}/></svg>;
}
function Button({icon,label,onClick,className='',...props}){return <button className={'scene-button '+className} onClick={onClick} aria-label={label} {...props}><Icon name={icon}/><span>{label}</span></button>;}
function Sheet({title,children,onClose,className=''}){
 const ref=useRef();useEffect(()=>{const d=ref.current,previous=document.activeElement;d.showModal();return()=>{d.close();if(previous?.isConnected)previous.focus();};},[]);
 return <dialog ref={ref} className={'scene-sheet '+className} aria-label={title} onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><header><h2>{title}</h2><Button icon="close" label="Close" onClick={onClose}/></header>{children}</dialog>;
}
function Particles({celebrate=false,opening=false,reduced=false}){
 const ref=useRef();useEffect(()=>{
  const canvas=ref.current,ctx=canvas.getContext('2d'),media=matchMedia('(prefers-reduced-motion: reduce)');let frame=0,start=0,hiddenAt=0,elapsed=0,finished=false,canceled=false;
  canvas.dataset.active='false';canvas.dataset.cards=String(celebrate?20:opening?16:0);
  if(reduced||media.matches||(!celebrate&&!opening)||!ctx)return;
  const duration=celebrate?4600:3400,cards=Array.from({length:celebrate?20:16},(_,i)=>{const image=new Image();image.src=asset('assets/cards/royal/'+['heart','spade','club','diamond'][i%4]+'_'+(i%13+1)+'.png');return {image,x:(i+.5)/(celebrate?20:16),phase:Math.random()*6,delay:i*22};});
  const sparks=Array.from({length:celebrate?28:8},()=>({x:Math.random(),y:Math.random(),r:1+Math.random()*2}));
  function finish(){finished=true;cancelAnimationFrame(frame);canvas.dataset.active='false';ctx.clearRect(0,0,canvas.width,canvas.height);}
  function draw(now){if(canceled||finished||document.hidden)return;if(document.documentElement.classList.contains('reduce-motion')){finish();return;}if(!start)start=now;elapsed=now-start;if(elapsed>=duration){finish();return;}
   const box=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio,1.5);if(canvas.width!==Math.round(box.width*dpr)||canvas.height!==Math.round(box.height*dpr)){canvas.width=Math.round(box.width*dpr);canvas.height=Math.round(box.height*dpr);}
   ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,box.width,box.height);canvas.dataset.active='true';const t=elapsed/duration;
   for(const c of cards){if(!c.image.complete||!c.image.naturalWidth)continue;const progress=Math.max(0,(elapsed-c.delay)/(duration-c.delay));ctx.save();ctx.globalAlpha=.62*(1-Math.max(0,t-.85)/.15);ctx.translate(c.x*box.width+Math.sin(t*3+c.phase)*20,(-.15+progress*1.35)*box.height);ctx.rotate(Math.sin(t*3+c.phase)*.45);ctx.drawImage(c.image,-23,-34,46,69);ctx.restore();}
   ctx.globalAlpha=(1-t)*.6;ctx.fillStyle='#ffe4ab';for(const p of sparks){ctx.beginPath();ctx.arc(p.x*box.width,(p.y+t*.2)%1*box.height,p.r,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;frame=requestAnimationFrame(draw);
  }
  function visibility(){if(document.hidden){hiddenAt=performance.now();cancelAnimationFrame(frame);canvas.dataset.active='false';}else if(!finished){if(start&&hiddenAt)start+=performance.now()-hiddenAt;hiddenAt=0;frame=requestAnimationFrame(draw);}}
  function motion(){if(media.matches)finish();}media.addEventListener('change',motion);document.addEventListener('visibilitychange',visibility);
  Promise.all(cards.map(c=>c.image.decode?.().catch(()=>{})||Promise.resolve())).then(()=>{if(!canceled&&!document.hidden&&!finished)frame=requestAnimationFrame(draw);});
  return()=>{canceled=true;cancelAnimationFrame(frame);document.removeEventListener('visibilitychange',visibility);media.removeEventListener('change',motion);};
 },[celebrate,opening,reduced]);return <canvas className="scene-particles" ref={ref} aria-hidden="true"/>;
}
function readStats(){try{return JSON.parse(localStorage.getItem('solitaire-friends-stats-v1'))||{};}catch{return {};}}
function Stats({onClose,audio}){
 const [compact,setCompact]=useState(matchMedia('(orientation:landscape) and (max-height:550px)').matches);useEffect(()=>{const media=matchMedia('(orientation:landscape) and (max-height:550px)');const change=()=>{setCompact(media.matches);setPage(0);};media.addEventListener('change',change);return()=>media.removeEventListener('change',change);},[]);const pageSize=compact?2:4;
 const s=readStats(),[page,setPage]=useState(0),[draw,setDraw]=useState('all');const scores=(s.highScores||[]).filter(x=>draw==='all'||String(x.draw)===draw),pages=Math.max(1,Math.ceil(scores.length/pageSize));
 return <Sheet title="Your best games" className="stats-sheet" onClose={onClose}><div className="records-summary"><div><strong>{s.wins||0}</strong><span>Wins</span></div><div><strong>{s.played?Math.round(100*s.wins/s.played):0}%</strong><span>Win rate</span></div><div><strong>{s.bestTime==null?'—':time(s.bestTime)}</strong><span>Fastest</span></div></div><label className="setting-row">Show<select value={draw} onChange={e=>{setDraw(e.target.value);setPage(0);}}><option value="all">All deals</option><option value="1">Draw 1</option><option value="3">Draw 3</option></select></label><div className="records-list">{scores.slice(page*pageSize,page*pageSize+pageSize).map((r,i)=><div className="record" key={r.date+'-'+i}><Icon name="trophy"/><strong>{r.score.toLocaleString()}</strong><span>{time(r.seconds)} · {r.moves} moves<br/>Draw {r.draw}{r.assisted?' · Assisted':''}</span></div>)}{!scores.length&&<p className="empty-records">Your first win belongs here.</p>}</div>{pages>1&&<div className="pager"><button disabled={!page} onClick={()=>setPage(page-1)}>Previous</button><span>{page+1} / {pages}</span><button disabled={page>=pages-1} onClick={()=>setPage(page+1)}>Next</button></div>}<p className="fine-print">Score rises as cards reach home. Winning score rewards fewer moves and less time. Records stay on this device.</p><Button icon="share" label="Share my best" onClick={async()=>{const m=await load('assets/js/share.js');await m.shareGame(scores[0]);audio?.sfx.tap();}}/></Sheet>;
}
function Settings({audio,onClose}){
 const [tab,setTab]=useState('sound'),[prefs,setPrefs]=useState({...audio.preferences});let storedBack='blue';try{storedBack=JSON.parse(localStorage.getItem('arline-deck-prefs'))?.back||'blue';}catch{}const [back,setBack]=useState(storedBack);
 function change(key,value){audio.sfx.unlock();audio.setPreference(key,value);setPrefs({...audio.preferences});}
 function chooseBack(id){setBack(id);document.documentElement.dataset.back=id;localStorage.setItem('arline-deck-prefs',JSON.stringify({back:id}));audio.sfx.tap();}
 return <Sheet title="Make it yours" onClose={onClose}><div className="sheet-tabs">{['sound','table'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>{setTab(t);audio.sfx.tap();}}>{t==='sound'?'Sound':'Cards & table'}</button>)}</div>{tab==='sound'?<div className="settings-grid"><label className="setting-row">Sound effects<input type="checkbox" checked={prefs.effects} onChange={e=>change('effects',e.target.checked)}/></label><label className="setting-row">Effects volume<input type="range" min="0" max="1" step=".05" value={prefs.effectsVolume} onChange={e=>change('effectsVolume',Number(e.target.value))}/></label><label className="setting-row">Background music<input type="checkbox" checked={prefs.music} onChange={e=>{audio.music.start();change('music',e.target.checked);}}/></label><label className="setting-row">Music volume<input type="range" min="0" max="1" step=".05" value={prefs.musicVolume} onChange={e=>change('musicVolume',Number(e.target.value))}/></label><label className="setting-row">Gentle vibration<input type="checkbox" checked={prefs.haptics} onChange={e=>change('haptics',e.target.checked)}/></label><Button icon="sound" label="Try the sounds" onClick={()=>{change('effects',true);audio.sfx.shuffle();setTimeout(()=>audio.sfx.mallet('hint'),1450);}}/><p className="fine-print audio-credit-note">Recorded audio credits are included with the game.</p></div>:<><label className="setting-row">Draw deck<select aria-label="Draw deck" value={prefs.deckOnRight?'right':'left'} onChange={e=>change('deckOnRight',e.target.value==='right')}><option value="right">Right side</option><option value="left">Left side</option></select></label><label className="setting-row">Reduced motion<input type="checkbox" checked={prefs.reducedMotion} onChange={e=>change('reducedMotion',e.target.checked)}/></label><div className="back-picker">{['blue','red','green','purple','charcoal','burgundy'].map(id=><button key={id} aria-pressed={back===id} onClick={()=>chooseBack(id)}><img src={asset('assets/cards/royal/back'+(id==='blue'?'':'-'+id)+'.jpg')} alt={id+' card back'}/><span>{id}</span></button>)}</div></>}</Sheet>;
}
function Title({audio,navigate,open,opening,onInstall}){
 const [entering,setEntering]=useState(false),[status,setStatus]=useState('');let resume=!!localStorage.getItem('solitaire-friends-game-v1');
 async function enter(){if(entering||!audio)return;audio.sfx.unlock();audio.setPreference('effects',true);if(audio.preferences.effectsVolume<.2)audio.setPreference('effectsVolume',.75);audio.sfx.launch();audio.music.start();setEntering(true);setTimeout(()=>navigate('game'),650);}
 return <main className={'title-scene '+(entering?'entering':'')}><Particles opening={opening} reduced={!!audio?.preferences.reducedMotion}/><div className="title-glow"/><header className="title-tools"><Button icon="trophy" label="Scores" onClick={()=>open('scores')}/><Button icon={audio?.preferences.effects?'sound':'mute'} label={audio?.preferences.effects?'Sound on':'Sound off'} onClick={()=>{audio?.sfx.unlock();audio?.sfx.toggleMute();audio?.sfx.mallet('open');}}/></header><div className="title-stage"><div className="title-halo"/><div className="title-card-fan" aria-hidden="true">{['spade_13','heart_1','club_12','diamond_1'].map((name,i)=><img key={name} style={{'--card-index':i}} src={asset('assets/cards/royal/'+name+'.png')} alt=""/>)}</div><img className="title-logo" src={asset('assets/title-640.webp')} width="640" height="350" alt="Solitaire and Friends" fetchPriority="high"/><div className="title-caption">A little magic. A familiar deck.</div></div><div className="title-start"><button id="startGame" className="start-button" onClick={enter} disabled={!audio||entering}><Icon name="play"/>{entering?'Let’s play!':resume?'Continue playing':'Play Solitaire'}</button><span className="sound-prompt">Tap to enter with card sounds</span></div><footer className="title-footer"><Button icon="cards" label="Install" onClick={onInstall}/><Button icon="settings" label="Settings" onClick={()=>open('settings')}/><Button icon="share" label="Share" onClick={async()=>{const m=await load('assets/js/share.js');setStatus(await m.shareGame());}}/></footer><p className="title-status" role="status">{status}</p></main>;
}
function Game({audio,navigate,open}){
 const board=useRef(),[ready,setReady]=useState(false),[hud,setHud]=useState({moves:0,elapsed:0,score:0,best:0,home:0,rewindsLeft:3,shufflesLeft:1,surprisesLeft:1,historyLength:0}),[message,setMessage]=useState('Tap or drag a card'),[tucked,setTucked]=useState(false);
 useEffect(()=>{let canceled=false,cleanup,timer;const state=e=>setHud(e.detail),say=e=>setMessage(e.detail),assets=e=>setReady(e.detail.ready),hint=e=>setHud(h=>({...h,hint:e.detail}));addEventListener('solitaire-state',state);addEventListener('solitaire-message',say);addEventListener('solitaire-hint',hint);addEventListener('solitaire-assets',assets);
  load('games/solitaire/solitaire.js').then(m=>{if(!canceled){cleanup=m.mountSolitaire(board.current);}}).catch(()=>setMessage('Could not open the game. Please reopen when online.'));
  const touch=()=>{setTucked(true);clearTimeout(timer);timer=setTimeout(()=>setTucked(false),1400);};board.current.addEventListener('pointerdown',touch);
  return()=>{canceled=true;cleanup?.();clearTimeout(timer);removeEventListener('solitaire-state',state);removeEventListener('solitaire-message',say);removeEventListener('solitaire-hint',hint);removeEventListener('solitaire-assets',assets);};
 },[]);
 const call=fn=>{audio?.sfx.unlock();window.__sol?.[fn]?.();};
 return <main className={'play-scene '+(tucked?'controls-tucked':'')}><header className="play-top"><Button icon="back" label="Home" onClick={()=>navigate('home')}/><div className="score-hud"><span>SCORE <strong id="score">{hud.score.toLocaleString()}</strong></span><span>BEST <strong id="highScore">{hud.best.toLocaleString()}</strong></span></div><button className="sound-mini" aria-label={audio?.preferences.effects?'Mute sound':'Enable sound'} onClick={()=>{audio?.sfx.unlock();audio?.sfx.toggleMute();audio?.sfx.tap();}}><Icon name={audio?.preferences.effects?'sound':'mute'}/></button><Button icon="settings" label="Settings" onClick={()=>open('settings')}/></header><div className="mini-hud"><span id="timer">{time(hud.elapsed)}</span><span id="moves">{hud.moves} moves</span><span id="progress">{hud.home} / 52</span></div><div className={'table-stage '+(!ready?'loading':'')}><div id="board" ref={board} className="board" role="region" aria-label="Solitaire table"/>{!ready&&<div className="table-loading">Your cards are coming…</div>}</div><div className={'context-cue '+(hud.hint?'has-hint':'')}><p id="hintText" role="status">{message}</p><button id="playHint" hidden={!hud.hint} onClick={()=>call('playHint')}><Icon name="play"/>Play move</button></div><footer className="play-dock"><Button id="hintBtn" icon="hint" label="Hint" className="hint-action" onClick={()=>call('hint')}/><Button id="rewindBtn" icon="undo" label="Undo" disabled={!hud.historyLength||hud.reversing} onClick={()=>call('rewind')}/><Button id="timeReverse" icon="reverse" label={'Reverse · '+hud.rewindsLeft} disabled={!hud.historyLength||!hud.rewindsLeft||hud.reversing} onClick={()=>call('timeReverse')}/><Button id="newDeal" icon="shuffle" label="Shuffle" className="shuffle-action" onClick={()=>open('deal')}/><Button id="surpriseBtn" icon="gift" label={'Surprise · '+hud.surprisesLeft} disabled={!hud.surprisesLeft||hud.reversing} onClick={()=>call('surprise')}/></footer><div id="win" className={'win scene-victory '+(hud.won?'show':'')} aria-hidden={!hud.won}>{hud.won&&<Particles celebrate reduced={!!audio?.preferences.reducedMotion}/>}<div className="victory-card"><Icon name="trophy"/><div className="victory-eyebrow">Beautifully played</div><h1>You did it!</h1><strong className="victory-score">{hud.score.toLocaleString()}</strong><p>{hud.score>=hud.best?'A personal best!':'Another lovely win.'}</p><div className="victory-stats"><span>{time(hud.elapsed)}<small>Time</small></span><span id="winMoves">{hud.moves}<small>Moves</small></span></div><button id="winNew" className="start-button" onClick={()=>window.__sol.newGame()}>Next deal</button><Button icon="share" label="Share my score" onClick={async()=>{const m=await load('assets/js/share.js');await m.shareGame(readStats().highScores?.[0]);}}/></div></div></main>;
}
function App(){
 const initial=location.pathname.endsWith('statistics.html')?'scores':location.pathname.includes('/games/solitaire')?'game':'home';const [screen,setScreen]=useState(initial==='scores'?'home':initial),[sheet,setSheet]=useState(initial==='scores'?'scores':null),[audio,setAudio]=useState(null),[version,setVersion]=useState(0);const [opening,setOpening]=useState(initial!=='game');const sheetRef=useRef(sheet);const [,setInstallTick]=useState(0);const installRef=useRef(),closeTimer=useRef();
 useEffect(()=>{audioPromise.then(setAudio);const change=()=>setVersion(v=>v+1);addEventListener('game-settings',change);const pop=()=>{if(sheetRef.current){const d=document.querySelector('.scene-sheet');if(d?.classList.contains('closing')){sheetRef.current=null;setSheet(null);}else{d?.classList.add('closing');closeTimer.current=setTimeout(()=>{sheetRef.current=null;setSheet(null);},160);}return;}setOpening(false);setSheet(null);setScreen(location.pathname.includes('/games/solitaire')?'game':'home');};addEventListener('popstate',pop);const install=e=>{e.preventDefault();installRef.current=e;setInstallTick(x=>x+1);};addEventListener('beforeinstallprompt',install);load('assets/js/sw-register.js');load('assets/js/game-surface.js');return()=>{removeEventListener('game-settings',change);removeEventListener('popstate',pop);removeEventListener('beforeinstallprompt',install);};},[]);
 useEffect(()=>{try{document.documentElement.dataset.back=JSON.parse(localStorage.getItem('arline-deck-prefs'))?.back||'blue';}catch{}},[]);
 function navigate(next){window.__sol?.save();setOpening(false);sheetRef.current=null;setSheet(null);history.pushState({},'',asset(next==='game'?'games/solitaire/':''));setScreen(next);}
 function open(value){clearTimeout(closeTimer.current);document.querySelector('.scene-sheet')?.classList.remove('closing');audio?.sfx.mallet('open');if(!sheetRef.current)history.pushState({...history.state,solitaireSheet:value},'',location.href);else history.replaceState({...history.state,solitaireSheet:value},'',location.href);sheetRef.current=value;setSheet(value);}
 function close(){audio?.sfx.mallet('close');document.querySelector('.scene-sheet')?.classList.add('closing');clearTimeout(closeTimer.current);closeTimer.current=setTimeout(()=>{if(history.state?.solitaireSheet)history.back();else{sheetRef.current=null;setSheet(null);}},160);}
 async function install(){if(installRef.current){await installRef.current.prompt();installRef.current=null;}else open('install');}
 const hud=window.__sol?.hud;
 return <><div className="app-scene" data-version={version}>{screen==='game'?<Game audio={audio} navigate={navigate} open={open}/>:<Title audio={audio} navigate={navigate} open={open} opening={opening} onInstall={install}/>}</div>{sheet==='settings'&&audio&&<Settings audio={audio} onClose={close}/ >}{sheet==='scores'&&<Stats onClose={close} audio={audio}/ >}{sheet==='deal'&&<Sheet title="Shuffle & play" onClose={close}><p className="sheet-note">A fresh deck starts a new game. Your current deal will be replaced.</p><div className="deal-options"><Button id="newGame" icon="shuffle" label="Shuffle a fresh deal" className="large-option" onClick={()=>{window.__sol.newGame();close();}}/><Button id="shuffleBtn" icon="star" label={'Mix hidden cards · '+(hud?.shufflesLeft||0)+' left'} disabled={!hud?.shufflesLeft} onClick={()=>{window.__sol.shuffle();close();}}/><Button icon="undo" label="Restart this deal" onClick={()=>{window.__sol.restart();close();}}/><Button icon="trophy" label="Daily deal" onClick={()=>{window.__sol.newGame('Daily');close();}}/><label className="setting-row">New deal draws<select id="drawMode" defaultValue={hud?.drawCount||1} onChange={e=>{window.__sol.newGame('Classic',Number(e.target.value));close();}}><option value="1">1 card</option><option value="3">3 cards</option></select></label><Button icon="play" label="Auto-finish" onClick={()=>{window.__sol.autoFinish();close();}}/></div></Sheet>}{sheet==='install'&&<Sheet title="Keep it on your phone" onClose={close}><p>In Android Chrome or Edge, open the browser menu and choose Install app or Add to Home screen. On iPhone, use Safari’s Share → Add to Home Screen.</p></Sheet>}</>;
}
createRoot(document.getElementById('root')).render(<App/>);
